### ISSUE TITLE
Deploy no Heroku

### ISSUE THREAD

**Issue by luisccf** [competdev/site_pet#1]
Criar conta do comPET no Heroku e subir a aplicação na plataforma.

**Comment by luisccf** [comment]
@higorFischer alguma previsão? Teremos uma reunião para levantamento de requisitos em breve e seria legal mostrar o que já fizemos.

**Comment by higorFischer** [comment]
https://www.youtube.com/watch?v=iRgSQTmA-N4
Aqui luis, nesse video o cara mostra como colocar um app no heroku junto com o db sql

**Comment by luisccf** [comment]
Ok @higorFischer, defini o prazo de entrega para domingo. Pode ser?

**Comment by higorFischer** [comment]
@luisccf entao luis, eu vou viajar quinta e so volto na segunda. E estou cheio de trabalho. entao acho que nao sera possivel

**Comment by higorFischer** [comment]
@luisccf Conversei com o @higorcoimbra, ele vai fazer isso luis Valeu

**Comment by higorcoimbra** [comment]
Amanha a noite farei, grato.
